export const RESTART_ON_REMOUNT = '@@saga-injector/restart-on-remount'
export const DAEMON = '@@saga-injector/daemon'
export const ONCE_TILL_UNMOUNT = '@@saga-injector/once-till-unmount'

export const META_TITLE = 'Title boilerplate'

export const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sem sem, feugiat ac auctor eu, facilisis venenatis dolor. Maecenas et quam sed leo accumsan molestie nec eu turpis. Donec id tempus orci. Duis vel augue tortor. Cras imperdiet est vitae ex varius, dapibus hendrerit ante dignissim. Aliquam vulputate mollis mattis. Sed elit felis, tincidunt placerat libero ac, pellentesque rhoncus quam. Duis consectetur, est sed consequat sodales, turpis erat pretium lacus, sed efficitur eros nibh vitae dui. Nam volutpat tincidunt felis, eu gravida ante fermentum eu.

Integer eget sagittis augue, elementum condimentum odio. Maecenas convallis scelerisque nibh non lacinia. Duis malesuada at felis ut venenatis. Nullam et iaculis ligula, eget cursus ligula. Cras tristique, eros ut maximus mollis, velit odio suscipit erat, vitae auctor tortor tortor efficitur dui. Nullam ut arcu vitae ligula molestie rutrum sit amet eget erat. Quisque eget felis sit amet justo efficitur fringilla in vel urna. Sed tristique a odio in iaculis. Nulla in malesuada enim, eget gravida eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce quis justo nibh. Nam porta nisi vitae dolor suscipit, ac elementum enim lacinia. Integer eu pellentesque diam.

Curabitur id malesuada elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam pretium dapibus ante eu facilisis. Cras turpis dui, tincidunt vel eleifend nec, pulvinar a ligula. Suspendisse ac massa rutrum, tincidunt turpis quis, fringilla magna. Donec metus ligula, malesuada ac dui ac, sagittis gravida tellus. Quisque hendrerit ipsum euismod, elementum lorem in, tristique enim. In sem ex, iaculis vitae blandit at, viverra quis ex.

Vestibulum eu imperdiet lacus, nec lobortis mi. Donec varius mauris purus, quis porttitor neque molestie quis. Sed congue congue lacinia. Pellentesque non felis non mi luctus gravida. Praesent pretium finibus purus sed venenatis. Donec maximus mi nec nulla suscipit, at tincidunt nunc tincidunt. Etiam ex lectus, varius non commodo nec, imperdiet nec odio. Etiam enim metus, imperdiet at tellus quis, posuere cursus dui.

Suspendisse ante augue, scelerisque at neque nec, aliquam hendrerit ipsum. Donec euismod felis vel sodales ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. In vitae risus tellus. Duis laoreet volutpat diam, et pulvinar nisl venenatis quis. Nulla ultricies malesuada neque, ac facilisis mauris condimentum id. Quisque eu sapien eget nunc suscipit efficitur vitae a lacus. Aliquam posuere augue in velit eleifend cursus. Quisque commodo dolor et erat dapibus, id suscipit nisi commodo. Donec elit diam, pretium vel tortor sed, vehicula ullamcorper mi.

Pellentesque ac purus vestibulum, gravida augue vel, interdum orci. Suspendisse congue nec ipsum in posuere. Suspendisse ac purus mattis neque viverra placerat. Suspendisse potenti. Nam id sollicitudin arcu, cursus imperdiet urna. Donec viverra nisl in mi lobortis fermentum. In ut tempor velit. Cras eget dapibus enim. Curabitur a dapibus ante, sed aliquet ligula. Vivamus purus tortor, pretium et leo in, varius convallis neque. In sit amet tellus vitae ex eleifend tincidunt. Donec blandit nibh non arcu egestas, eu venenatis orci rhoncus. Sed lectus ante, molestie id bibendum id, condimentum ultrices dolor. In luctus, libero dictum maximus consequat, sapien risus venenatis diam, et consequat eros lacus vitae ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Aliquam posuere vitae dui in placerat. Nullam ac consequat ipsum. Donec imperdiet ex at felis sagittis, a scelerisque urna mattis. Aenean porta mauris ultrices, efficitur justo vitae, blandit justo. Mauris ac turpis eu massa sagittis tincidunt vitae sit amet mi. Donec id vehicula justo. Integer semper magna a nunc ornare, ut pretium ante lacinia. Nam eleifend vel lectus in cursus. Quisque et ipsum erat. Pellentesque dignissim molestie vulputate. Phasellus efficitur molestie felis nec sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut ullamcorper imperdiet eros at accumsan.

Sed posuere efficitur purus quis laoreet. Nunc id lacus sed elit porta tempus. Phasellus sed purus et ante consectetur mollis. Nulla sagittis massa sed rhoncus lobortis. Quisque id leo lorem. Ut leo odio, vehicula id pellentesque ac, ultricies at augue. Cras rhoncus massa ut metus luctus sagittis. Cras sed mollis lacus. Sed nec nunc et urna faucibus maximus. Morbi at efficitur arcu. Integer mollis ac diam sed interdum. Nulla mollis turpis nisl, at posuere neque dictum sed. Nunc malesuada justo quis ante convallis, non ornare erat porta.

Fusce nec libero aliquet, dignissim dui ut, dapibus dolor. In vitae vestibulum urna. Phasellus mattis placerat elit eget dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis et ligula ultricies, sagittis velit dapibus, suscipit orci. Curabitur at dolor eget diam porta sollicitudin. Phasellus a lacinia ante. Nulla facilisi. Vestibulum id pellentesque est. Integer ut consequat turpis. Nulla sit amet lectus lectus. Morbi venenatis metus nulla, ut ullamcorper nibh venenatis eu. Aenean a volutpat nibh. Sed erat neque, aliquet a porta vel, scelerisque ut libero. Suspendisse imperdiet et diam in congue. Ut quis consequat tortor.

Praesent nec sodales massa, quis eleifend dui. Pellentesque eu mi lobortis, cursus lorem sit amet, venenatis massa. Nullam a gravida justo, eu faucibus erat. Vivamus maximus nibh magna, id semper tortor facilisis a. Vivamus semper, lectus at dignissim aliquet, lacus diam tempus orci, sed aliquet ipsum enim euismod mauris. Donec pulvinar, augue vel tristique sollicitudin, risus nulla iaculis sem, id laoreet orci eros sit amet enim. Maecenas ultricies lectus augue, quis facilisis lectus sodales id. Curabitur eu dui tellus. Proin mattis sagittis tortor sit amet interdum.

Quisque iaculis efficitur metus, vitae dignissim urna finibus ut. Donec at interdum velit. Proin volutpat arcu nec pulvinar imperdiet. Cras tellus magna, luctus id tristique non, consequat non neque. Suspendisse luctus sapien orci, ut malesuada orci egestas ac. Vivamus congue lorem elit, ac convallis libero consectetur at. Nullam laoreet viverra erat et imperdiet.

Etiam nisi elit, mattis blandit sodales sit amet, pharetra faucibus mauris. Morbi luctus magna quis lacus maximus facilisis. Vivamus ut dapibus nisl, sed suscipit lorem. Nullam sem lorem, pellentesque in diam sit amet, varius semper nisl.`

export const theme = {
  black: {
    default: '#000',
  },
}
